name: metl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch::pytorch=2.6.0
  - pytorch::torchvision
  - pytorch::pytorch-cuda=12.8
  - lightning=2.5.1
  - torchmetrics=1.7.1
  - numpy=1.26.4
  - pandas=2.0.3
  - scipy=1.13.1
  - scikit-learn=1.4.2
  - networkx=3.3
  - tqdm=4.66.2
  - pyyaml=6.0
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - biopandas=0.4.1
  - shortuuid=1.0.1
  - umap-learn=0.5.6
  - bokeh=3.4.1
  - datashader=0.16.2
  - holoviews=1.19.1
  - colorcet=3.1.0
  - pynndescent=0.5.13
  - jupyter=1.0.0
  - jupyterlab=4.1.8
  - ipywidgets=8.1.2
  - requests=2.31.0
  - pytables=3.9.2
  - pip=24.0
  - wandb=0.17.1
  - tensorboard=2.17.0
  - memory_profiler=0.61.0
  - rich=13.7.0
  - pyqt=5.15.9
  - sqlalchemy=2.0.30
  - aenum=3.1.15
  - connectorx=0.3.2
  - configargparse=1.7
  - torchinfo=1.8.0
  - biopython=1.83
  - pip:
      - jsonargparse[signatures]==4.33.1
      - matplotlib-label-lines==0.7.0
      - fair-esm==2.0.0
      - torchextractor==0.3.0
      - adjusttext==0.8
